server:
  port: 8803

spring:
  application:
    name: spring-cloud-swagger-service3
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true
        health-check-interval: 15s
        health-check-url: http://${spring.cloud.consul.host}:${server.port}/health
management:
  security:
    enabled: false

logging:
  level:
    com.battcn: debug


