server:
  port: 8802

spring:
  application:
    name: spring-cloud-swagger-service2
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true
  swagger:
    base-package: com.battcn
management:
  security:
    enabled: false


